[package]
name = "zerometry"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4"
bytemuck = "1.23.1"
geo-types = "0.7.16"
geo = "0.30.0"

[dev-dependencies]
geojson = "0.24.2" # only used to display stuff in case of unexpected errors
insta = "1.43.1"
proptest = "1.4"
